### PR TITLE
fix: error in Kubelet when using default root directory

### LINKED ISSUE #288: Kubelet log has error when use default root dir
The log(combined contaienrd and kubelet):

> Dec 12 11:34:51 kind-control-plane containerd[2874]: time="2022-12-12T11:34:51.360081705Z" level=debug msg=ImageFsInfo
Dec 12 11:34:51 kind-control-plane containerd[2874]: time="2022-12-12T11:34:51.360168006Z" level=debug msg="ImageFsInfo returns filesystem info [&FilesystemUsage{Timestamp:1670844891360135406,FsId:&FilesystemIdentifier{Mountpoint:/var/lib/containerd/io.containerd.snapshotter.v1.nydus,},UsedBytes:&UInt64Value{Value:0,},InodesUsed:&UInt64Value{Value:0,},}]"
Dec 12 11:34:51 kind-control-plane kubelet[601]: E1212 11:34:51.360778     601 cri_stats_provider.go:455] "Failed to get the info of the filesystem with mountpoint" err="failed to get device for dir \"/var/lib/containerd/io.containerd.snapshotter.v1.nydus\": stat failed on /var/lib/containerd/io.containerd.snapshotter.v1.nydus with error: no such file or directory" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.nydus"

Continerd returns a [fixed-format directory](https://github.com/containerd/containerd/blob/f2cf411b79fab1cb95ae1bc968c8f35b5f4eef35/pkg/cri/server/service.go#L348-L350) for snapshotters:

```golang
func imageFSPath(rootDir, snapshotter string) string {
	return filepath.Join(rootDir, fmt.Sprintf("%s.%s", plugin.SnapshotPlugin, snapshotter))
}
```

### PR DESCRIPTION
**Pull request by fappy1234567**
## Relevant Issue 
Fixes #288 
## Details
Setting the snapshotter's default root path to /var/lib/containerd/io.containerd.snapshotter.v1.nydus can resolve the issue.

### CODE REVIEW

**Comment by imeoer** [comment]
Thanks for the PR! but it seems the string `/var/lib/containerd-nydus` is across multiple files, can we correct them all?

**Comment by fappy1234567** [comment]
@imeoer Thank you for your feedback and review! I have checked and updated the string /var/lib/containerd-nydus across all relevant files, except for two yaml files in the \tests\e2e\k8s directory. Please review the changes and let me know if there's anything else that needs to be adjusted.

**Comment by imeoer** [comment]
@fappy1234567 Thanks, I think there's no reason to keep `tests/e2e/k8s`, and the `README.md` needs also to be updated. :)

**Comment by fappy1234567** [comment]
@imeoer I've already updated the README.md. Let me know if there's anything else that needs attention.

**Comment by imeoer** [comment]
@fappy1234567 Thanks, the `tests/e2e/k8s` also need to be updated.

**Comment by fappy1234567** [comment]
@imeoer Thank you for your guidance. I have also updated the tests/e2e/k8s section, but there are some checks that are not passing. When you have a moment, could you please take a look and see if there is anything that needs to be adjusted? Thank you very much!

**Review by imeoer — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
