### PR TITLE
support registry multi mirrors

### PR DESCRIPTION
**Pull request by raoxiang1996**
Add mirror config to toml configuration file
Use the toml file to configure the startup parameters of nydus-snapshotter
relates to [dragonflyoss/image-service#790](https://github.com/dragonflyoss/image-service/pull/790)
Signed-off-by: raoxiang raoxiang1996@gmail.com

### CODE REVIEW

**Comment by changweige** [comment]
Um... I am re-designing the nydus-snapshotter toml configuration file format. So let's pend this PR until the final format id decided. It will have a structural format that is more suggestive and easy to be used.

**Comment by raoxiang1996** [comment]
> 
OK, then I will wait for the format design to complete and resubmit

**Comment by raoxiang1996** [comment]
> Um... I am re-designing the nydus-snapshotter toml configuration file format. So let's pend this PR until the final format id decided. It will have a structural format that is more suggestive and easy to be used.

OK, I will wait for the file format design to complete and resubmit

**Comment by changweige** [comment]
Nydus-snapshotter's own toml based configuration file has almost been achieved now. The mirror registry configuration can be added to it now if you are still interested. Please try to follow containerd's mirror registry configuration style so nydus-snapshotter does not need to restart itsefl.

**Pull request closed without merging**
