### PR TITLE
cmd: move nydus-overlayfs from image service to snapshotter

### PR DESCRIPTION
**Pull request by jiangliu**
Nydus-overlayfs is a mount helper for nydus-snapshotter, and is only used by nydus-snapshotter. So move it from Image Service into nydus-snapshotter.

### CODE REVIEW

**Comment by imeoer** [comment]
Maybe also add some build commands in `Makefile`.

**Comment by jiangliu** [comment]
> Maybe also add some build commands in `Makefile`.

Done, add build target for nydus-overlayfs

**Comment by imeoer** [comment]
It seems have some broken CIs: https://github.com/containerd/nydus-snapshotter/actions/runs/6105239526/job/16568447263?pr=529

**Comment by jiangliu** [comment]
> It seems have some broken CIs: https://github.com/containerd/nydus-snapshotter/actions/runs/6105239526/job/16568447263?pr=529

Add one step for CI in makefile, now works.

**Comment by imeoer** [comment]
Does this binary is included in the release package? After we removed it from the `image-service` repo, there was no place to download it.

**Comment by jiangliu** [comment]
> Does this binary is included in the release package? After we removed it from the `image-service` repo, there was no place to download it.

It should be included, but I'm not familiar with github release. So which github file should I modify?

**Comment by imeoer** [comment]
@jiangliu Should be `.github/workflows/release.yml`, not sure it has been included.

**Comment by jiangliu** [comment]
> @jiangliu Should be `.github/workflows/release.yml`, not sure it has been included.

done

**Review by changweige — APPROVED** [review]
LGTM

**Review by imeoer — APPROVED** [review]
LGTM

**Pull request merged**
