### PR TITLE
backend: support s3 backend

### PR DESCRIPTION
**Pull request by loheagn**
Signed-off-by: Nan Li <loheagn@icloud.com>

### CODE REVIEW

**Comment by loheagn** [comment]
update dragonflyoss/image-service#831

**Comment by loheagn** [comment]
Hi, the CI seems to be blocked by something has nothing to do with this PR. Can anyone please help to rerun the failed job? Thanks :)

**Comment by changweige** [comment]
How should we test it?

**Review by imeoer — APPROVED** [review]
LGTM! Thanks @loheagn

**Comment by loheagn** [comment]
@changweige @imeoer Hi, I added a new smoke test to this patch to test the s3 backend. You can review the code again :)

**Comment by imeoer** [comment]
@loheagn It seems a data race be detected in https://github.com/containerd/nydus-snapshotter/actions/runs/3695539855/jobs/6258056733. :)

**Comment by loheagn** [comment]
> @loheagn It seems a data race be detected in https://github.com/containerd/nydus-snapshotter/actions/runs/3695539855/jobs/6258056733. :)

@imeoer  Thanks for pointing the error! Tha data race was fixed.

**Review by changweige — APPROVED** [review]
Very nice test, thanks

**Pull request merged**
