### PR TITLE
remove scheme field in nydusd config

### PR DESCRIPTION
**Pull request by imeoer**
remove scheme field in nydusd config

We have implemented automatically scheme detect for nydusd in this PR:

https://github.com/dragonflyoss/image-service/pull/893#merged-event

So we can remove the default scheme field in nydusd config file.

### CODE REVIEW

**Comment by changweige** [comment]
Seems no logic changes in this change set?

**Comment by liubogithub** [comment]
Looks good for the 1st commit.

**Comment by changweige** [comment]
We need to discuss the arrangement of currently scattered documents. I am inclining to merge this change until the nydusd (v2.2) including automatically changing HTTP scheme is released which means it can actually be used.

**Comment by changweige** [comment]
Needs rebase. Can we only submit the changes for reference nydusd config file in this PR and clean up the docs in the next step?

**Review by changweige — APPROVED** [review]

**Pull request merged**
